name: "Deploy UiPath Package"
on:
  push:
    branches:
      - "*"

jobs:
  compile:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup UiPath (uipcli) command line tool
        uses: Mikael-RnD/setup-uipath@v1

      - name: Pack UiPath project
        run: |
          foreach($package in Get-ChildItem -Path ${{ github.workspace }} -Recurse -Filter project.json -File) {
            uipcli package pack "$package" -o "${{ github.workspace }}\output }}" --outputType Tests
            dir "${{ github.workspace }}\output }}"
            uipcli package deploy "${{ github.workspace }}\output\baidu_Tests.1.0.0.nupkg" "https://cloud.uipath.com" "${{secrets.TEST_TENANT_NAME}}" -A ${{secrets.ACCOUNT_NAME}} -I ${{secrets.OAUTH_CLIENT_ID}} -S "${{secrets.OAUTH_CLIENT_SECRET}}" -o "Shared" --applicationScope "OR.Folders.Read OR.Settings.Read"
          }
